In [14]:
import pandas as pd

In [15]:
df_04 = pd.DataFrame(pd.read_csv("D:/My_projects/Capstone_project/data/raw/04_monthly_sip_inflows.csv"))
df_04

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN
5,2022-06,12276,5.60,7.50,5.18,NaN
6,2022-07,12140,5.65,9.21,5.25,NaN
7,2022-08,12694,5.71,8.90,5.31,NaN
8,2022-09,12976,5.80,9.40,5.41,NaN
9,2022-10,13040,5.93,9.52,5.55,NaN
10,2022-11,13306,6.00,8.80,5.62,NaN
11,2022-12,13573,6.05,7.60,5.70,NaN
12,2023-01,13856,6.13,9.10,5.82,20.31
13,2023-02,13687,6.19,8.20,5.88,19.66
14,2023-03,14276,6.32,10.00,6.01,15.80
15,2023-04,14749,6.41,9.25,6.15,24.33
16,2023-05,14749,6.50,8.70,6.22,20.05
17,2023-06,14734,6.55,7.90,6.30,20.02
18,2023-07,15245,6.65,9.80,6.45,25.58
19,2023-08,15814,6.73,9.10,6.58,24.58
20,2023-09,16042,6.82,10.20,6.72,23.63
21,2023-10,16928,6.91,9.50,6.90,29.82
22,2023-11,17073,7.00,8.80,7.05,28.31
23,2023-12,17610,7.10,8.40,7.18,29.74
24,2024-01,18838,7.20,9.60,7.35,35.96
25,2024-02,19187,7.30,8.50,7.52,40.18
26,2024-03,20371,7.40,9.00,7.71,42.69
27,2024-04,20371,7.60,9.40,7.90,38.12
28,2024-05,21262,7.78,8.90,8.15,44.16
29,2024-06,21262,7.90,8.20,8.35,44.31
30,2024-07,23332,8.00,10.00,8.56,53.05
31,2024-08,23547,8.11,9.80,8.78,48.90
32,2024-09,24509,8.22,9.20,8.98,52.78
33,2024-10,25323,8.30,9.55,9.22,49.59
34,2024-11,25320,8.40,9.10,9.45,48.30
35,2024-12,26459,8.50,9.30,9.70,50.25
36,2025-01,26400,8.22,9.10,13.00,40.14
37,2025-02,25999,8.30,8.60,13.18,35.50
38,2025-03,25926,8.11,7.80,13.35,27.27
39,2025-04,26632,8.38,46.00,13.55,30.73
40,2025-05,26688,8.50,9.20,13.72,25.52
41,2025-06,27274,8.62,9.50,13.88,28.28
42,2025-07,28464,8.75,10.20,14.05,22.00
43,2025-08,28265,8.85,9.80,15.18,20.04
44,2025-09,29361,9.00,10.50,15.38,19.80
45,2025-10,29529,9.10,9.45,15.55,16.61
46,2025-11,30200,9.20,9.10,15.72,19.27
47,2025-12,31002,9.35,9.80,15.90,17.17

In [16]:
df_04.shape

(48, 6)

In [17]:
df_04.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [18]:
df_04.columns

Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='str')

In [19]:
df_04.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [20]:
df_04.tail()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
43,2025-08,28265,8.85,9.80,15.18,20.04
44,2025-09,29361,9.00,10.50,15.38,19.80
45,2025-10,29529,9.10,9.45,15.55,16.61
46,2025-11,30200,9.20,9.10,15.72,19.27
47,2025-12,31002,9.35,9.80,15.90,17.17

In [21]:
df_04.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [22]:
df_04.describe(include="all")

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
count,48,48.000000,48.000000,48.000000,48.000000,36.000000
unique,48,NaN,NaN,NaN,NaN,NaN
top,2022-01,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,19577.520833,7.189583,9.893750,8.632083,31.456944
std,NaN,6354.329621,1.271457,5.370745,3.613579,11.768190
min,NaN,11438.000000,4.910000,7.500000,4.800000,15.800000
25%,NaN,13658.500000,6.110000,8.775000,5.790000,20.245000
50%,NaN,18224.000000,7.150000,9.200000,7.265000,28.295000
75%,NaN,25944.250000,8.300000,9.562500,10.525000,40.807500
max,NaN,31002.000000,9.350000,46.000000,15.900000,53.050000

In [23]:
df_04.isna().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [24]:
df_04['yoy_growth_pct'] = df_04['yoy_growth_pct'].fillna(df_04['yoy_growth_pct'].mean)

In [25]:
df_04.isna().sum()

month                        0
sip_inflow_crore             0
active_sip_accounts_crore    0
new_sip_accounts_lakh        0
sip_aum_lakh_crore           0
yoy_growth_pct               0
dtype: int64

In [26]:
df_04.duplicated().sum()

np.int64(0)