In [1]:
import pandas as pd

In [2]:
df_06 = pd.DataFrame(pd.read_csv("D:/My_projects/Capstone_project/data/raw/06_industry_folio_count.csv"))
df_06

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48
5,2023-04,15.54,10.88,2.18,0.93,1.55
6,2023-07,16.28,11.40,2.28,0.98,1.63
7,2023-10,16.72,11.70,2.34,1.00,1.67
8,2024-01,17.78,12.45,2.49,1.07,1.78
9,2024-04,18.85,13.20,2.64,1.13,1.89
10,2024-07,19.98,13.99,2.80,1.20,2.00
11,2024-10,21.62,15.13,3.03,1.30,2.16
12,2024-12,22.89,16.02,3.20,1.37,2.29
13,2025-01,23.10,16.17,3.23,1.39,2.31
14,2025-03,23.45,16.42,3.28,1.41,2.35
15,2025-04,23.89,16.72,3.34,1.43,2.39
16,2025-07,24.57,17.20,3.44,1.47,2.46
17,2025-08,24.89,17.42,3.48,1.49,2.49
18,2025-09,25.19,17.63,3.53,1.51,2.52
19,2025-10,25.60,17.92,3.58,1.54,2.56
20,2025-12,26.12,18.28,3.66,1.57,2.61

In [3]:
df_06.shape

(21, 6)

In [4]:
df_06.columns

Index(['month', 'total_folios_crore', 'equity_folios_crore',
       'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore'],
      dtype='str')

In [5]:
df_06.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [6]:
df_06.tail()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
16,2025-07,24.57,17.20,3.44,1.47,2.46
17,2025-08,24.89,17.42,3.48,1.49,2.49
18,2025-09,25.19,17.63,3.53,1.51,2.52
19,2025-10,25.60,17.92,3.58,1.54,2.56
20,2025-12,26.12,18.28,3.66,1.57,2.61

In [7]:
df_06.dtypes

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [8]:
df_06.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [9]:
df_06.describe(include="all")

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
count,21,21.000000,21.000000,21.000000,21.000000,21.000000
unique,21,NaN,NaN,NaN,NaN,NaN
top,2022-01,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,19.829524,13.880476,2.776190,1.190000,1.983333
std,NaN,4.583376,3.207799,0.640308,0.274864,0.459079
min,NaN,13.260000,9.280000,1.860000,0.800000,1.330000
25%,NaN,15.540000,10.880000,2.180000,0.930000,1.550000
50%,NaN,19.980000,13.990000,2.800000,1.200000,2.000000
75%,NaN,23.890000,16.720000,3.340000,1.430000,2.390000
max,NaN,26.120000,18.280000,3.660000,1.570000,2.610000

In [10]:
df_06.isna().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [11]:
df_06.duplicated().sum()

np.int64(0)